#include<iostream>  //iostream is called header file or lib: 
//It is used to display the output
//In C++, the #include directive is used to include a header file in a source file
using namespace std; 

int main() // main() is a fun that is entry point of a program
// from main() funtion program start to excute  
{
    std::cout<<"Beta"; // cout is an object of class iostream or
    // it is module of iostream lib: 
    // cout  used to display the output to the standard output device
    // where << is called insertion 

    return 0;  //return 0; statement is used to indicate that the main function has completed
    // or if we don't use that its ok
    }
